########### install files ###############

install(FILES
    BreezeDark.colors
    BreezeHighContrast.colors
    BreezeLight.colors
    KritaNeutral.colors
    KritaBlender.colors
    KritaBright.colors
    KritaDark.colors
    KritaDarkOrange.colors
    KritaDarker.colors
    DESTINATION ${KDE_INSTALL_DATADIR}/color-schemes
)


